#!/usr/bin/env ruby

require './JobSearch.rb'
fail ArgumentError, "Usage:  Job offers [category]\n" if ARGV.count == 0
category = ARGV[0]

jobs_found = JobSearch::Tecoloco.getjobs(category)

jobs_found.each do |title, date, city|
  puts "Job offer:#{title} in #{city} until #{date}."
end
